services:
  app:
    build: .
    environment:
      EXERCISM_TOKEN: <exercism_token>
      EXERCISM_EVENTS_DB_HOST: database
      EXERCISM_EVENTS_DB_USER: postgres
      EXERCISM_EVENTS_DB_PASSWORD: admin
      EXERCISM_EVENTS_DB_NAME: postgres
      EXERCISM_EVENTS_DB_PORT: 5432
    depends_on:
      - "database"
  database:
    image: postgres:alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
